# Generated by Django 6.0.6 on 2026-09-29 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General & Positioning'), ('services', 'Services & Deliverables'), ('process', 'Process & Timelines'), ('pricing', 'Pricing & Engagements')], default='general', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Salons, Aesthetic Clinics, Hairstylists', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('subtitle', models.CharField(max_length=255)),
                ('the_challenge', models.TextField(help_text='Common digital mismatch for this beauty sector')),
                ('the_solution', models.TextField(help_text='How Quorv connects branding, web, and booking')),
                ('key_focus', models.CharField(help_text='e.g. Visual distinction, local search, frictionless booking', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Industry Specialization',
                'verbose_name_plural': 'Industry Specializations',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=140)),
                ('business_type', models.CharField(choices=[('salon', 'Hair / Beauty Salon'), ('aesthetic_clinic', 'Aesthetic Clinic / Medspa'), ('hairstylist', 'Independent Hairstylist / Colorist'), ('barber', 'Luxury Barbershop'), ('nail_lash', 'Nail / Lash Studio'), ('spa_wellness', 'Spa & Wellness Sanctuary'), ('beauty_brand', 'Independent Beauty Brand'), ('other', 'Other Beauty Professional')], default='salon', max_length=40)),
                ('country', models.CharField(blank=True, help_text='e.g. UK, USA, UAE, Canada, Australia', max_length=80)),
                ('service_interest', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('source', models.CharField(default='Website Form', max_length=80)),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('contacted', 'Contacted via WhatsApp/Email'), ('in_discussion', 'In Discussion / Scoping'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inquiry Lead',
                'verbose_name_plural': 'Inquiry Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('client_type', models.CharField(help_text='e.g. Aesthetic Clinic Concept / Hair Studio System', max_length=100)),
                ('category', models.CharField(default='Brand & Digital System', max_length=80)),
                ('concept_summary', models.TextField()),
                ('deliverables', models.CharField(help_text='e.g. Visual Identity, Web Architecture, Booking Experience', max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_concept', models.BooleanField(default=True, help_text='Clearly distinguishes design concepts from client work until case studies exist.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio Concept',
                'verbose_name_plural': 'Portfolio Concepts',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Brand, Digital, Content, Growth', max_length=60)),
                ('code', models.CharField(help_text='e.g. 01, 02, 03, 04', max_length=10)),
                ('outcome_statement', models.CharField(help_text='e.g. Make your business recognizable before someone walks through the door.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=220)),
                ('outcome', models.TextField(help_text='Concrete business outcome for a beauty business')),
                ('full_description', models.TextField(blank=True)),
                ('deliverables', models.TextField(help_text='Comma-separated or newline-separated deliverables')),
                ('whatsapp_prompt', models.CharField(default="Hi Quorv, I'm interested in discussing this service for my beauty business.", help_text='Prefilled message for WhatsApp CTA', max_length=255)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category__order', 'order'],
            },
        ),
    ]
