# Generated by Django 6.1.1 on 2026-09-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('whatsapp_click', 'WhatsApp CTA Click'), ('email_click', 'Email CTA Click'), ('lead_submit', 'Lead Form Submission'), ('service_view', 'Service Page View'), ('concept_view', 'Concept View'), ('outbound_link', 'Outbound Link Click')], max_length=40)),
                ('event_label', models.CharField(help_text='e.g. Hero WhatsApp CTA, Category 02 Digital', max_length=255)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversion Analytics Event',
                'verbose_name_plural': 'Conversion Analytics Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
