# Generated by Django 6.1.1 on 2026-09-30 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analyticsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('subtitle', models.CharField(max_length=300)),
                ('category', models.CharField(help_text='e.g. Salon Website Architecture, Med Spa Systems, Booking Integration', max_length=100)),
                ('read_time', models.CharField(default='5 min read', max_length=30)),
                ('summary', models.TextField(help_text='Concise executive summary for AI search and quick human scanning')),
                ('content', models.TextField(help_text='Full markdown or HTML content')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Studio Insight',
                'verbose_name_plural': 'Studio Insights',
                'ordering': ['order', '-published_date'],
            },
        ),
    ]
