# Generated by Django 6.0.6 on 2026-10-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAuditSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('website_or_instagram', models.CharField(help_text='Current website URL or @handle', max_length=200)),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('business_type', models.CharField(help_text='e.g. Aesthetic Clinic, Salon, Medspa', max_length=80)),
                ('booking_software', models.CharField(help_text='e.g. Fresha, Phorest, Vagaro, Boulevard, None', max_length=80)),
                ('primary_challenge', models.CharField(help_text='e.g. Look outdated, low booking conversion, poor Google ranking', max_length=150)),
                ('current_monthly_revenue', models.CharField(blank=True, max_length=80)),
                ('calculated_score', models.IntegerField(default=68, help_text='Calculated health score out of 100')),
                ('key_vulnerabilities', models.TextField(blank=True, help_text='Identified leakages e.g. Booking friction, mobile bounce')),
                ('status', models.CharField(choices=[('pending', 'Audit Pending Review'), ('analyzed', 'Score Generated / Sent'), ('booked_consult', 'Booked Consultation'), ('closed', 'Closed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Digital Audit Submission',
                'verbose_name_plural': 'Digital Audit Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
