# Generated by Django 6.1.1 on 2026-10-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_digitalauditsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('instagram_click', 'Instagram DM CTA Click'), ('whatsapp_click', 'WhatsApp CTA Click'), ('email_click', 'Email CTA Click'), ('lead_submit', 'Lead Form Submission'), ('service_view', 'Service Page View'), ('concept_view', 'Concept View'), ('outbound_link', 'Outbound Link Click')], max_length=40),
        ),
        migrations.AlterField(
            model_name='portfolioconcept',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image URL or static path (e.g. /static/... or https://...)', max_length=500),
        ),
    ]
