# Generated by Django 6.0.6 on 2026-10-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_elan_concept_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='image_url',
            field=models.CharField(blank=True, help_text='Sector showcase image URL or static path', max_length=500),
        ),
    ]
